# Generated by Django 2.0.4 on 2018-04-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0001_create_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='somemodel',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
